name: Release Creation

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Update system.json using jq
        run: |
          jq --arg version "${{ github.event.release.tag_name }}" \
             --arg url "https://github.com/${{ github.repository }}" \
             --arg manifest "https://github.com/${{ github.repository }}/releases/latest/download/system.json" \
             --arg download "https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/system.zip" \
             '
             .version = $version |
             .url = $url |
             .manifest = $manifest |
             .download = $download
             ' system.json > tmp.json && mv tmp.json system.json

      - name: Create System Archive
        run: |
          zip --recurse-paths ./system.zip \
            system.json hellsing.mjs templates/ styles/ module/ lang/

      - name: Update Release with Files
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: ${{ github.event.release.name }}
          draft: ${{ github.event.release.draft }}
          prerelease: ${{ github.event.release.prerelease }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./system.json, ./system.zip"
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
